//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCost.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost_Type
    {
        public string CostTypeID { get; set; }
        public string CostTypeName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserName { get; set; }
    }
}
