//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCost.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home_User
    {
        public string UserID { get; set; }
        public string UserLoginAccount { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
    }
}
