//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCost.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home_Cost
    {
        public string ID { get; set; }
        public System.DateTime CostDate { get; set; }
        public string CostType { get; set; }
        public double CostAmount { get; set; }
        public string CostDesc { get; set; }
        public string CreateBy { get; set; }
    }
}
