//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCost.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home_Cost
    {
        public string ID { get; set; }
        public System.DateTime CostDate { get; set; }
        public string CostType { get; set; }
        public double CostAmount { get; set; }
        public string CostDesc { get; set; }
        public string CreateByUserID { get; set; }
        public string CreateByUserAccount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
